In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
import numpy
import pickle

pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)
arry = numpy.array(y)

X = X/255.0

model = Sequential()

model.add(Conv2D(6,3,3,input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, arry, batch_size=32, epochs=3, validation_split=0.3)

Epoch 1/3
115/115 [==============================] - 4s 36ms/step - loss: 0.3637 - accuracy: 0.8828 - val_loss: 0.1515 - val_accuracy: 0.9419
Epoch 2/3
115/115 [==============================] - 4s 35ms/step - loss: 0.1007 - accuracy: 0.9617 - val_loss: 0.1038 - val_accuracy: 0.9617
Epoch 3/3
115/115 [==============================] - 4s 34ms/step - loss: 0.0917 - accuracy: 0.9663 - val_loss: 0.1257 - val_accuracy: 0.9495


[[[[ 57]
   [ 66]
   [ 70]
   ...
   [ 14]
   [  5]
   [  0]]

  [[ 59]
   [ 64]
   [ 69]
   ...
   [ 10]
   [  1]
   [  0]]

  [[ 56]
   [ 59]
   [ 64]
   ...
   [  9]
   [  0]
   [  0]]

  ...

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]

  [[  0]
   [  0]
   [  0]
   ...
   [  0]
   [  0]
   [  0]]]


 [[[  7]
   [ 10]
   [ 16]
   ...
   [ 61]
   [ 73]
   [ 73]]

  [[  7]
   [ 14]
   [ 17]
   ...
   [ 38]
   [ 54]
   [ 59]]

  [[  7]
   [ 21]
   [ 21]
   ...
   [ 27]
   [ 30]
   [ 37]]

  ...

  [[ 39]
   [ 11]
   [ 21]
   ...
   [ 19]
   [  9]
   [ 40]]

  [[ 17]
   [ 24]
   [ 21]
   ...
   [ 19]
   [ 27]
   [ 15]]

  [[ 18]
   [ 16]
   [ 21]
   ...
   [ 19]
   [ 15]
   [ 16]]]


 [[[ 41]
   [ 45]
   [ 45]
   ...
   [ 64]
   [ 61]
   [ 54]]

  [[ 42]
   [ 45]
   [ 46]
   ...
   [ 66]
   [ 63]
   [ 58]]

  [[ 45]
   [ 41]
   [ 46]
   ...
   [ 68]
   [ 68]
   [ 59]]

  ...

  [[  0]
   [  0]
   [  0]
   